name: Sync Upcoming Contests

on:
  schedule:
    - cron: "0 22 * * *" # 4:00 AM IST

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Daily cron job
        run: |
          curl -L -X POST 'https://events-tutly.vercel.app/api/cron/sync-upcomming-contests' \
          -H "Content-Type: application/json"
